version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "arn:aws:s3:::angular-app-buck11-tv2"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@next
  build:
    commands:
        - echo Build started 
        - npm run build
  post_build:
    commands:
        - aws s3 cp s3://angular-app-buck11-tv2/Procfile ./dist
        - aws s3 cp s3://angular-app-buck11-tv2/.npmrc ./dist
        - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
 
artifacts:
    files:
        - '**/*'
    base-directory: 'dist'